---
title: "🇨🇦 Canadian ATI Archive"
output: 
  html_document:
    toc: FALSE
---

### Accessing government information can be tricky. We want to make it easier.

<font size = 4> Every year journalists, academics, lawyers, and members of the public file tens of thousands of requests for information from the Canadian Government. But previously filed Access to Information (ATI) requests aren't made public by default. That's why we are working to develop the Canadian ATI Archive!

Currently, you can find summaries of previously completed requests on Canada's [Open Government website](https://open.canada.ca/en/search/ati). If you find one you want, you can fill out a web form requesting access. If you want more than one, you have to complete the form multiple times. Usually, information is released on a CD or USB key as a PDF that you can't search for text or copy and paste.

We published hundreds of previously filed ATI requests that go back as far as 2014 through [Pinpoint](https://journaliststudio.google.com/pinpoint/collections&utm_source=caij), a Google tool that uses artificial intelligence to identify text in the PDF files as well as advanced information retrieval techniques to quickly search through huge amounts of content.

Right now our collection features files from the [Department of Justice](https://journaliststudio.google.com/pinpoint/search?collection=545b02bfc4d44314&utm_source=caij), the [Canada Border Services Agency](https://journaliststudio.google.com/pinpoint/search?collection=a2fd1411cad7fb36&utm_source=caij), and the [Canada Security Intelligence Service](https://journaliststudio.google.com/pinpoint/search?collection=b2c31ff7297a47f7&utm_source=caij). We will continue expanding the number of documents available in the coming months.

It's often helpful to see the wording of the original request. Unfortunately, completed summaries are only kept in the public dataset for two years. Our mirror of the public dataset updates weekly and features summaries going back to 2017. You can [download](https://github.com/lchski/gc-ati-summaries-data/blob/main/ati-summaries.csv) the whole dataset or [query](https://gc-ati-summaries-data.labs.lucascherkewski.com/summaries/summaries) it using this SQL query builder. \font

# Quicklinks to ATI resources:
 - Public ATI collections on Google [Pinpoint](https://journaliststudio.google.com/pinpoint/collections&utm_source=caij) maintained by Jamie Duncan & Alex Luscombe from the University of Winnipeg Centre for Access to Information and Justice
 - Previously completed requests [data set mirror](https://github.com/lchski/gc-ati-summaries-data) developed by Lucas Cherkewsky
 - Form auto-fillers developed by Tom Cardoso: [Piggyback](https://tomcardoso.github.io/piggyback/) for previously completed requests and [ATIPster](https://tomcardoso.github.io/atipster/) for new requests.
 





